nav:
- Home: index.md
- Requirements: requirements.md
- Installation: installation.md
- Usage: usage.md
- About:
  - License: license.md
  - Release Notes: https://github.com/project-sthali/sthali-backend/releases
  - Issue Tracker: https://github.com/project-sthali/sthali-backend/issues
- API Reference:
  - AppSpecification: api/class_AppSpecification.md
  - Config: api/class_Config.md
  - SthaliBackend: api/class_SthaliBackend.md
  - default_lifespan: api/function_default_lifespan.md
repo_name: sthali-backend
repo_url: https://github.com/project-sthali/sthali-backend/
site_author: Jhunu Fernandes
site_description: A FastAPI package for implement services
site_name: sthali-backend
site_url: https://project-sthali.github.io/sthali-backend/
theme: readthedocs
